PIPELINE-2054: Improve testing | Part I: utils
GlobalFishingWatch/pipe-segment pull request #185
Opened 2024-06-19 21:26 UTC by tomaslink

2025-04-14 21:51 UTC, smpiano commented on .coveragerc
> +    sandbox
sorry but where `sandbox` folder is use?

2025-04-14 21:51 UTC, smpiano commented on pipe_segment/transform/read_messages.py
> +    DATE({{ filter_field }})
Here when the `filter_field` is `_TABLE_SUFFIX` for the sharded date tables the `_table_suffix` takes the format `YYYYMMDD` how tables suffix is and `DATE()` cannot cast it that way.

2025-04-14 21:52 UTC, smpiano approved these changes
A bunch of good changes and really good that you added test of the transformations.
LGTM. Just added question and comments.

2025-04-15 01:39 UTC, tomaslink commented on .coveragerc
> +    sandbox
I think there was some code that was unused and I moved that into sandbox folder (experimental code) in a previous PR.

2025-04-15 01:45 UTC, tomaslink commented on pipe_segment/transform/write_sink.py
> +from ..tools import datetime_from_timestamp
PEP8 recommends absolute imports: https://peps.python.org/pep-0008/#imports. 

I tend to use absolute imports unless there is a pretty good reason to use relative imports (for example, some internal package that I know I want to extract to other place/library and I don't want to have to change all the internal imports to remove the previous parent packages).

2025-04-15 01:57 UTC, tomaslink commented on pipe_segment/transform/read_messages.py
> +    DATE({{ filter_field }})
I see before the same template: 
```python
def filter_messages(self, start_date: datetime, end_date: datetime) -> str:
    template = self.filter_template
    if template is None:
        template = "DATE({{ filter_field }}) " + \
            "BETWEEN '{{ start_date.strftime(date_format) }}' " + \
            " AND '{{ end_date.strftime(date_format) }}'"

    filter = Template(template).render({'start_date': start_date,
                                        'end_date': end_date,
                                        'filter_field': self._filtering_field,
                                        'date_format': self._date_format,
                                        })
    return filter
 ```

https://github.com/GlobalFishingWatch/pipe-segment/blob/develop/pipe_segment/models/bigquery_message_source.py#L59

What am I missing?

2025-04-15 17:23 UTC, tomaslink commented on pipe_segment/transform/read_messages.py
> +    DATE({{ filter_field }})
@smpiano @andres-arana

2025-04-15 19:54 UTC, smpiano commented on pipe_segment/transform/read_messages.py
> +    DATE({{ filter_field }})
@tomaslink yes, that cast was done previously checking the `develop` history and introduced the bug, the change is not in the latest release.
The motive of the `DATE()` cast is good for partitioned tables, they use a time related field, mostly a `timestamp` field type and the condition `WHERE timestamp BETWEEN start_date AND end_date` implies the inclusion of the end_date at `00:00:00` and not the whole end_date, with `DATE(timestamp)` that is solved. If that field
For sharded date tables the `DATE()` cast does not work because it is trying to do

2025-05-05 16:43 UTC, andres-arana requested changes
Small comments

2025-05-05 16:43 UTC, andres-arana commented on Dockerfile
> -ENTRYPOINT ["/opt/apache/beam/boot"]
Beam boot should be set as entrypoint only for prod

2025-05-05 16:43 UTC, andres-arana commented on compose.yaml
>        - "gcp:/root/.config/"
Extract common config between services.

2025-05-05 16:43 UTC, andres-arana commented on Makefile
>  VENV_NAME:=.venv
See if we can include here the makefile that we have on pipe-nmea

2025-05-05 22:12 UTC, tomaslink commented on Dockerfile
> -ENTRYPOINT ["/opt/apache/beam/boot"]
Now that I think about it, I think it makes sense to have this entrypoint in the section in which we are installing apache beam system dependencies...But what we can do is to modify the entry point in the dev target. What do you think?

2025-05-06 01:33 UTC, merged